language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "artjcod"
    token:
      secure: '$SONAR_TOKEN'

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=artjcod_TennisMatch
  - mvn cobertura:cobertura 
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - bash <(curl -s https://codecov.io/bash)
