language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "artjcod"
    token:
      secure: "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"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=artjcod_TennisMatch
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - bash <(curl -s https://codecov.io/bash)
